python run_longExp.py \
    --is_training 1 \
    --root_path ./dataset/ \
    --data_path ETTh1.csv \
    --model_id ETTh1_336_96 \
    --model DREAM_STL \
    --data ETTh1 \
    --features M \
    --seq_len 336 \
    --pred_len 96 \
    --enc_in 7 \
    --batch_size 32 \
    --learning_rate 0.005 \
    --des Exp \
    --itr 1